package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtActiorInfo;

public interface RmtActiorInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int insert(RmtActiorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int insertSelective(RmtActiorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    RmtActiorInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int updateByPrimaryKeySelective(RmtActiorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(RmtActiorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_actior_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int updateByPrimaryKey(RmtActiorInfo record);
}