package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtDepartmentChartInfo;

public interface RmtDepartmentChartInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int insert(RmtDepartmentChartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int insertSelective(RmtDepartmentChartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    RmtDepartmentChartInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int updateByPrimaryKeySelective(RmtDepartmentChartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int updateByPrimaryKey(RmtDepartmentChartInfo record);
}