package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtDepartmentInfo;

public interface RmtDepartmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int insert(RmtDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int insertSelective(RmtDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    RmtDepartmentInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int updateByPrimaryKeySelective(RmtDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_info
     *
     * @mbggenerated Thu Jul 09 17:07:45 CST 2020
     */
    int updateByPrimaryKey(RmtDepartmentInfo record);
}