package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtOrganizationExtendInfo;

public interface RmtOrganizationExtendInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int insert(RmtOrganizationExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int insertSelective(RmtOrganizationExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    RmtOrganizationExtendInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int updateByPrimaryKeySelective(RmtOrganizationExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Wed May 20 15:46:04 CST 2020
     */
    int updateByPrimaryKey(RmtOrganizationExtendInfo record);
}