package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtUserDepartmentInfo;

public interface RmtUserDepartmentInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int insert(RmtUserDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int insertSelective(RmtUserDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    RmtUserDepartmentInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int updateByPrimaryKeySelective(RmtUserDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int updateByPrimaryKey(RmtUserDepartmentInfo record);
}