package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtUserInfo;

public interface RmtUserInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int insert(RmtUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int insertSelective(RmtUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    RmtUserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int updateByPrimaryKeySelective(RmtUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_info
     *
     * @mbggenerated Tue Jun 02 11:46:37 CST 2020
     */
    int updateByPrimaryKey(RmtUserInfo record);
}