package com.mg.node.db.sql.pojo;

public class MTcRolePrivilegeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_tc_role_privilege_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_tc_role_privilege_info.roleId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_tc_role_privilege_info.privilegeId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_tc_role_privilege_info.id
     *
     * @return the value of m_tc_role_privilege_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_tc_role_privilege_info.id
     *
     * @param id the value for m_tc_role_privilege_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_tc_role_privilege_info.roleId
     *
     * @return the value of m_tc_role_privilege_info.roleId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_tc_role_privilege_info.roleId
     *
     * @param roleId the value for m_tc_role_privilege_info.roleId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_tc_role_privilege_info.privilegeId
     *
     * @return the value of m_tc_role_privilege_info.privilegeId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_tc_role_privilege_info.privilegeId
     *
     * @param privilegeId the value for m_tc_role_privilege_info.privilegeId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
}