package com.mg.node.db.sql.pojo;

public class MTcUserRoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_tc_user_role_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_tc_user_role_info.userId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_tc_user_role_info.roleId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_tc_user_role_info.id
     *
     * @return the value of m_tc_user_role_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_tc_user_role_info.id
     *
     * @param id the value for m_tc_user_role_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_tc_user_role_info.userId
     *
     * @return the value of m_tc_user_role_info.userId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_tc_user_role_info.userId
     *
     * @param userId the value for m_tc_user_role_info.userId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_tc_user_role_info.roleId
     *
     * @return the value of m_tc_user_role_info.roleId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_tc_user_role_info.roleId
     *
     * @param roleId the value for m_tc_user_role_info.roleId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}