package com.mg.node.db.sql.pojo;

import java.util.Date;

public class MTdActionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.url
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Date timeCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.privilege
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String privilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.siteId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.id
     *
     * @return the value of m_td_action_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.id
     *
     * @param id the value for m_td_action_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.url
     *
     * @return the value of m_td_action_info.url
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.url
     *
     * @param url the value for m_td_action_info.url
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.displayName
     *
     * @return the value of m_td_action_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.displayName
     *
     * @param displayName the value for m_td_action_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.timeCreated
     *
     * @return the value of m_td_action_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Date getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.timeCreated
     *
     * @param timeCreated the value for m_td_action_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.privilege
     *
     * @return the value of m_td_action_info.privilege
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.privilege
     *
     * @param privilege the value for m_td_action_info.privilege
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.siteId
     *
     * @return the value of m_td_action_info.siteId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.siteId
     *
     * @param siteId the value for m_td_action_info.siteId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }
}