package com.mg.node.db.sql.pojo;

import java.util.Date;

public class MTdPrivilegeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_privilege_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_privilege_info.pname
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_privilege_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_privilege_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Date timeCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_privilege_info.level
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_privilege_info.prority
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Integer prority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_privilege_info.id
     *
     * @return the value of m_td_privilege_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_privilege_info.id
     *
     * @param id the value for m_td_privilege_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_privilege_info.pname
     *
     * @return the value of m_td_privilege_info.pname
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_privilege_info.pname
     *
     * @param pname the value for m_td_privilege_info.pname
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_privilege_info.displayName
     *
     * @return the value of m_td_privilege_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_privilege_info.displayName
     *
     * @param displayName the value for m_td_privilege_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_privilege_info.timeCreated
     *
     * @return the value of m_td_privilege_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Date getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_privilege_info.timeCreated
     *
     * @param timeCreated the value for m_td_privilege_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_privilege_info.level
     *
     * @return the value of m_td_privilege_info.level
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_privilege_info.level
     *
     * @param level the value for m_td_privilege_info.level
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_privilege_info.prority
     *
     * @return the value of m_td_privilege_info.prority
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Integer getPrority() {
        return prority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_privilege_info.prority
     *
     * @param prority the value for m_td_privilege_info.prority
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setPrority(Integer prority) {
        this.prority = prority;
    }
}