package com.mg.node.db.sql.pojo;

public class MTdRoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_role_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_role_info.roleName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_role_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_role_info.siteId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Integer siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_role_info.id
     *
     * @return the value of m_td_role_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_role_info.id
     *
     * @param id the value for m_td_role_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_role_info.roleName
     *
     * @return the value of m_td_role_info.roleName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_role_info.roleName
     *
     * @param roleName the value for m_td_role_info.roleName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_role_info.displayName
     *
     * @return the value of m_td_role_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_role_info.displayName
     *
     * @param displayName the value for m_td_role_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_role_info.siteId
     *
     * @return the value of m_td_role_info.siteId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_role_info.siteId
     *
     * @param siteId the value for m_td_role_info.siteId
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }
}