package com.mg.node.db.sql.pojo;

import java.util.Date;

public class MTdUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.name
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.password
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.weixin
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.weibo
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.qq
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.telephone
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Date timeCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.level
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.stataDelete
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Integer stataDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.timeDelete
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    private Date timeDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.id
     *
     * @return the value of m_td_user_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.id
     *
     * @param id the value for m_td_user_info.id
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.name
     *
     * @return the value of m_td_user_info.name
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.name
     *
     * @param name the value for m_td_user_info.name
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.password
     *
     * @return the value of m_td_user_info.password
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.password
     *
     * @param password the value for m_td_user_info.password
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.weixin
     *
     * @return the value of m_td_user_info.weixin
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.weixin
     *
     * @param weixin the value for m_td_user_info.weixin
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.weibo
     *
     * @return the value of m_td_user_info.weibo
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.weibo
     *
     * @param weibo the value for m_td_user_info.weibo
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.qq
     *
     * @return the value of m_td_user_info.qq
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.qq
     *
     * @param qq the value for m_td_user_info.qq
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.telephone
     *
     * @return the value of m_td_user_info.telephone
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.telephone
     *
     * @param telephone the value for m_td_user_info.telephone
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.displayName
     *
     * @return the value of m_td_user_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.displayName
     *
     * @param displayName the value for m_td_user_info.displayName
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.timeCreated
     *
     * @return the value of m_td_user_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Date getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.timeCreated
     *
     * @param timeCreated the value for m_td_user_info.timeCreated
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setTimeCreated(Date timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.level
     *
     * @return the value of m_td_user_info.level
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.level
     *
     * @param level the value for m_td_user_info.level
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.stataDelete
     *
     * @return the value of m_td_user_info.stataDelete
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Integer getStataDelete() {
        return stataDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.stataDelete
     *
     * @param stataDelete the value for m_td_user_info.stataDelete
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setStataDelete(Integer stataDelete) {
        this.stataDelete = stataDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.timeDelete
     *
     * @return the value of m_td_user_info.timeDelete
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public Date getTimeDelete() {
        return timeDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.timeDelete
     *
     * @param timeDelete the value for m_td_user_info.timeDelete
     *
     * @mbggenerated Mon Sep 07 16:58:41 CST 2020
     */
    public void setTimeDelete(Date timeDelete) {
        this.timeDelete = timeDelete;
    }
}