package com.mg.node.db.sql.pojo;

import java.util.Date;

public class MTdUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.id
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.name
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.password
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.weixin
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.weibo
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.qq
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.telephone
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.displayName
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private String displayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.timeCreated
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private Date timecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.level
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.stataDelete
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private Integer statadelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_user_info.timeDelete
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    private Date timedelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.id
     *
     * @return the value of m_td_user_info.id
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.id
     *
     * @param id the value for m_td_user_info.id
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.name
     *
     * @return the value of m_td_user_info.name
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.name
     *
     * @param name the value for m_td_user_info.name
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.password
     *
     * @return the value of m_td_user_info.password
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.password
     *
     * @param password the value for m_td_user_info.password
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.weixin
     *
     * @return the value of m_td_user_info.weixin
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.weixin
     *
     * @param weixin the value for m_td_user_info.weixin
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.weibo
     *
     * @return the value of m_td_user_info.weibo
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.weibo
     *
     * @param weibo the value for m_td_user_info.weibo
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.qq
     *
     * @return the value of m_td_user_info.qq
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.qq
     *
     * @param qq the value for m_td_user_info.qq
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.telephone
     *
     * @return the value of m_td_user_info.telephone
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.telephone
     *
     * @param telephone the value for m_td_user_info.telephone
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.displayName
     *
     * @return the value of m_td_user_info.displayName
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.displayName
     *
     * @param displayname the value for m_td_user_info.displayName
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.timeCreated
     *
     * @return the value of m_td_user_info.timeCreated
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public Date getTimecreated() {
        return timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.timeCreated
     *
     * @param timecreated the value for m_td_user_info.timeCreated
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setTimecreated(Date timecreated) {
        this.timecreated = timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.level
     *
     * @return the value of m_td_user_info.level
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.level
     *
     * @param level the value for m_td_user_info.level
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.stataDelete
     *
     * @return the value of m_td_user_info.stataDelete
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public Integer getStatadelete() {
        return statadelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.stataDelete
     *
     * @param statadelete the value for m_td_user_info.stataDelete
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setStatadelete(Integer statadelete) {
        this.statadelete = statadelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_user_info.timeDelete
     *
     * @return the value of m_td_user_info.timeDelete
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public Date getTimedelete() {
        return timedelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_user_info.timeDelete
     *
     * @param timedelete the value for m_td_user_info.timeDelete
     *
     * @mbggenerated Fri Aug 14 11:15:32 CST 2020
     */
    public void setTimedelete(Date timedelete) {
        this.timedelete = timedelete;
    }
}