package com.mg.node.db.sql.pojo;

import java.util.Date;

public class MTdActionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.id
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.url
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.displayName
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    private String displayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_action_info.timeCreated
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    private Date timecreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.id
     *
     * @return the value of m_td_action_info.id
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.id
     *
     * @param id the value for m_td_action_info.id
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.url
     *
     * @return the value of m_td_action_info.url
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.url
     *
     * @param url the value for m_td_action_info.url
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.displayName
     *
     * @return the value of m_td_action_info.displayName
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.displayName
     *
     * @param displayname the value for m_td_action_info.displayName
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_action_info.timeCreated
     *
     * @return the value of m_td_action_info.timeCreated
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public Date getTimecreated() {
        return timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_action_info.timeCreated
     *
     * @param timecreated the value for m_td_action_info.timeCreated
     *
     * @mbggenerated Sun Jul 26 15:10:15 GMT+08:00 2020
     */
    public void setTimecreated(Date timecreated) {
        this.timecreated = timecreated;
    }
}