package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtPrivilegeGroupInfo;

public interface RmtPrivilegeGroupInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insert(RmtPrivilegeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insertSelective(RmtPrivilegeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    RmtPrivilegeGroupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKeySelective(RmtPrivilegeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKey(RmtPrivilegeGroupInfo record);
}