package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtPrivilegeInfo;

public interface RmtPrivilegeInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insert(RmtPrivilegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insertSelective(RmtPrivilegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    RmtPrivilegeInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKeySelective(RmtPrivilegeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKey(RmtPrivilegeInfo record);
}