package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtTenantExtendInfo;

public interface RmtTenantExtendInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_tenant_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_tenant_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insert(RmtTenantExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_tenant_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insertSelective(RmtTenantExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_tenant_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    RmtTenantExtendInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_tenant_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKeySelective(RmtTenantExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_tenant_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKey(RmtTenantExtendInfo record);
}