package com.mg.node.db.sql.mapper;

import com.mg.node.db.sql.pojo.RmtUserExtendInfo;

public interface RmtUserExtendInfoBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insert(RmtUserExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int insertSelective(RmtUserExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    RmtUserExtendInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKeySelective(RmtUserExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend_info
     *
     * @mbggenerated Thu Jul 09 17:17:20 CST 2020
     */
    int updateByPrimaryKey(RmtUserExtendInfo record);
}