package com.mg.node.db.sql.pojo;

public class MTdSysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.id
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.name
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.showType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Integer showtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.controlType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Integer controltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.value
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.dataSource
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String datasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.description
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.siteId
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Long siteid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.id
     *
     * @return the value of m_td_sys_config.id
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.id
     *
     * @param id the value for m_td_sys_config.id
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.name
     *
     * @return the value of m_td_sys_config.name
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.name
     *
     * @param name the value for m_td_sys_config.name
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.showType
     *
     * @return the value of m_td_sys_config.showType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Integer getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.showType
     *
     * @param showtype the value for m_td_sys_config.showType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setShowtype(Integer showtype) {
        this.showtype = showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.controlType
     *
     * @return the value of m_td_sys_config.controlType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Integer getControltype() {
        return controltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.controlType
     *
     * @param controltype the value for m_td_sys_config.controlType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setControltype(Integer controltype) {
        this.controltype = controltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.value
     *
     * @return the value of m_td_sys_config.value
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.value
     *
     * @param value the value for m_td_sys_config.value
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.dataSource
     *
     * @return the value of m_td_sys_config.dataSource
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.dataSource
     *
     * @param datasource the value for m_td_sys_config.dataSource
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.description
     *
     * @return the value of m_td_sys_config.description
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.description
     *
     * @param description the value for m_td_sys_config.description
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.siteId
     *
     * @return the value of m_td_sys_config.siteId
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Long getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.siteId
     *
     * @param siteid the value for m_td_sys_config.siteId
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }
}