package com.mg.node.db.sql.pojo;

public class MTdSysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.id
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.name
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.showType
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private Integer showType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.controlType
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private Integer controlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.value
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.dataSource
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private String dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.description
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.siteId
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    private Long siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.id
     *
     * @return the value of m_td_sys_config.id
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.id
     *
     * @param id the value for m_td_sys_config.id
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.name
     *
     * @return the value of m_td_sys_config.name
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.name
     *
     * @param name the value for m_td_sys_config.name
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.showType
     *
     * @return the value of m_td_sys_config.showType
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public Integer getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.showType
     *
     * @param showType the value for m_td_sys_config.showType
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setShowType(Integer showType) {
        this.showType = showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.controlType
     *
     * @return the value of m_td_sys_config.controlType
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public Integer getControlType() {
        return controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.controlType
     *
     * @param controlType the value for m_td_sys_config.controlType
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setControlType(Integer controlType) {
        this.controlType = controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.value
     *
     * @return the value of m_td_sys_config.value
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.value
     *
     * @param value the value for m_td_sys_config.value
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.dataSource
     *
     * @return the value of m_td_sys_config.dataSource
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.dataSource
     *
     * @param dataSource the value for m_td_sys_config.dataSource
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.description
     *
     * @return the value of m_td_sys_config.description
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.description
     *
     * @param description the value for m_td_sys_config.description
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.siteId
     *
     * @return the value of m_td_sys_config.siteId
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.siteId
     *
     * @param siteId the value for m_td_sys_config.siteId
     *
     * @mbggenerated Tue Aug 18 21:06:41 GMT+08:00 2020
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }
}