package com.mg.node.db.sql.pojo;

public class MTdSysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.id
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.configName
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.showType
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private Integer showType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.controlType
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private Integer controlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.configValue
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.dataSource
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private String dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.description
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_config.siteId
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    private Long siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.id
     *
     * @return the value of m_td_sys_config.id
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.id
     *
     * @param id the value for m_td_sys_config.id
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.configName
     *
     * @return the value of m_td_sys_config.configName
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.configName
     *
     * @param configName the value for m_td_sys_config.configName
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.showType
     *
     * @return the value of m_td_sys_config.showType
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public Integer getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.showType
     *
     * @param showType the value for m_td_sys_config.showType
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setShowType(Integer showType) {
        this.showType = showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.controlType
     *
     * @return the value of m_td_sys_config.controlType
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public Integer getControlType() {
        return controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.controlType
     *
     * @param controlType the value for m_td_sys_config.controlType
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setControlType(Integer controlType) {
        this.controlType = controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.configValue
     *
     * @return the value of m_td_sys_config.configValue
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.configValue
     *
     * @param configValue the value for m_td_sys_config.configValue
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.dataSource
     *
     * @return the value of m_td_sys_config.dataSource
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.dataSource
     *
     * @param dataSource the value for m_td_sys_config.dataSource
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.description
     *
     * @return the value of m_td_sys_config.description
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.description
     *
     * @param description the value for m_td_sys_config.description
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_config.siteId
     *
     * @return the value of m_td_sys_config.siteId
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_config.siteId
     *
     * @param siteId the value for m_td_sys_config.siteId
     *
     * @mbggenerated Mon Sep 07 15:13:11 CST 2020
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }
}