package com.mg.node.db.sql.pojo;

import java.util.Date;

public class MTdSysSite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_site.id
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_site.siteName
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String sitename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_site.password
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_site.displayName
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private String displayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_site.siteType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Integer sitetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_td_sys_site.timeCreated
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    private Date timecreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_site.id
     *
     * @return the value of m_td_sys_site.id
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_site.id
     *
     * @param id the value for m_td_sys_site.id
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_site.siteName
     *
     * @return the value of m_td_sys_site.siteName
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_site.siteName
     *
     * @param sitename the value for m_td_sys_site.siteName
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setSitename(String sitename) {
        this.sitename = sitename == null ? null : sitename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_site.password
     *
     * @return the value of m_td_sys_site.password
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_site.password
     *
     * @param password the value for m_td_sys_site.password
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_site.displayName
     *
     * @return the value of m_td_sys_site.displayName
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_site.displayName
     *
     * @param displayname the value for m_td_sys_site.displayName
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_site.siteType
     *
     * @return the value of m_td_sys_site.siteType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Integer getSitetype() {
        return sitetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_site.siteType
     *
     * @param sitetype the value for m_td_sys_site.siteType
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setSitetype(Integer sitetype) {
        this.sitetype = sitetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_td_sys_site.timeCreated
     *
     * @return the value of m_td_sys_site.timeCreated
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public Date getTimecreated() {
        return timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_td_sys_site.timeCreated
     *
     * @param timecreated the value for m_td_sys_site.timeCreated
     *
     * @mbggenerated Mon Aug 03 15:52:40 CST 2020
     */
    public void setTimecreated(Date timecreated) {
        this.timecreated = timecreated;
    }
}